- name: remove existing Docker packages
  become: true
  become_method: su
  dnf:
    name:
      - docker
      - docker-client
      - docker-client-latest
      - docker-common
      - docker-latest
      - docker-latest-logrotate
      - docker-logrotate
      - docker-engine
      - podman 
      - containers-common
    state: absent

- name: enable docker repository
  get_url:
    url: https://download.docker.com/linux/centos/docker-ce.repo
    dest: /etc/yum.repos.d/docker-ce.repo
    mode: '0644'
  become: true
  become_method: su

- name: install docker
  dnf:
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io
    state: present
  become: true
  become_method: su

- name: install docker compose
  get_url:
    url:  https://github.com/docker/compose/releases/download/v2.18.1/docker-compose-linux-x86_64
    dest: /usr/local/bin/docker-compose
    mode: '0755'
  become: true
  become_method: su

- name: add user to docker group
  user:
    name: "{{ ansible_user_id }}"
    groups: docker
    append: true
  become: true
  become_method: su